CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    department VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE module_departments (
    module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    department VARCHAR(20) NOT NULL,
    PRIMARY KEY (module_id, department)
);

CREATE TABLE module_incompatibilities (
    module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    incompatible_module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    PRIMARY KEY (module_id, incompatible_module_id)
);

CREATE TABLE module_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    module_id BIGINT NOT NULL REFERENCES modules(id),
    status VARCHAR(20) NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE access_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol VARCHAR(32) NOT NULL UNIQUE,
    justification VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    urgent BOOLEAN NOT NULL DEFAULT FALSE,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    denied_reason VARCHAR(255),
    requester_department VARCHAR(20) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    parent_request_id BIGINT REFERENCES access_requests(id)
);

CREATE TABLE access_request_modules (
    request_id BIGINT NOT NULL REFERENCES access_requests(id) ON DELETE CASCADE,
    module_id BIGINT NOT NULL REFERENCES modules(id),
    PRIMARY KEY (request_id, module_id)
);

CREATE TABLE access_request_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES access_requests(id) ON DELETE CASCADE,
    event_type VARCHAR(20) NOT NULL,
    description VARCHAR(256) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
